(*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.*)

let even_Fibo_sum n =
  let rec even_Fibo_sum_aux acc1 acc2 acc3 =
    if acc2 >= n then acc3
    else if (acc1 + acc2) mod 2 = 0 then
      even_Fibo_sum_aux acc2 (acc1+acc2) (acc1+acc2+acc3)
    else even_Fibo_sum_aux acc2 (acc1+acc2) acc3
  in even_Fibo_sum_aux 1 1 0

let() = Printf.printf"%d \n"(even_Fibo_sum 4000000)