(* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th
triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
  1,3,6,10,15,21,28,36,45,55,...
Let us list the factors of the first seven triangle numbers:
  1: 1
  3: 1,3
  6: 1,2,3,6
  10: 1,2,5,10
  15: 1,3,5,15
  21: 1,3,7,21
  28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?*)

let numbers_divisors n =
  let rec numbers_divisors_aux d i acc =
    if d * d > i then
      if i > 1 then
        acc * 2
      else
        acc
    else if i mod d = 0 then
      let rec count i c =
        if i mod d = 0 then
          count (i / d) (c + 1)
        else
          (i, c)
      in
      let (i, c) = count i 0 in
      numbers_divisors_aux (d + 1) i (acc * (c + 1))
    else
      numbers_divisors_aux (d + 1) i acc
  in
numbers_divisors_aux 2 n 1

let triangle_number_divisors divisors =
  let rec triangle_number_divisors_aux n =
    let triangle_number = (n * (n + 1)) / 2 in
    if numbers_divisors(triangle_number) > divisors then
      triangle_number
    else
      triangle_number_divisors_aux (n + 1)
  in
  triangle_number_divisors_aux 1
  
let () =
  let result = triangle_number_divisors 500 in 
  Printf.printf "The value of the first triangle number to have over five hundred divisors is: %d\n" result